version: "3.9"

services:
    backend:
        build: ./backend
        container_name: url-shortener-backend
        ports:
            - "${BACKEND_PORT:-3000}:3000"
        env_file:
            - ./backend/.env
        volumes:
            - ./backend/uploads:/app/uploads
            - ./backend:/app
            - /app/node_modules
        restart: unless-stopped
        command: npm run dev
        networks:
            - app_network
        depends_on:
            - mongo
            - redis

    frontend:
        build: ./frontend
        container_name: url-shortener-frontend
        ports:
            - "${FRONTEND_PORT:-3030}:3030"
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend:/app
            - /app/node_modules
        restart: unless-stopped
        command: npm run dev
        networks:
            - app_network
        depends_on:
            - backend

    mongo:
        image: mongo:7
        container_name: url-shortener-mongo
        restart: unless-stopped
        env_file:
            - ./backend/.env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_NAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - "${MONGO_PORT:-27017}:27017"
        volumes:
            - ./mongo_data:/data/db
            - ./logs/mongo:/var/log/mongodb
        command: mongod --quiet --logpath /var/log/mongodb/mongod.log --logappend
        networks:
            - app_network

    redis:
        image: redis:7
        container_name: url-shortener-redis
        restart: unless-stopped
        command: redis-server --appendonly yes
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - ./redis_data:/data
        networks:
            - app_network

volumes:
    mongo_data:
    redis_data:

networks:
    app_network:
        driver: bridge
