version: "3.9"

services:
    app:
        build: .
        container_name: url-shortener-app
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - mongo
            - redis
        volumes:
            - ./uploads:/app/uploads
        restart: unless-stopped

    mongo:
        image: mongo:7
        container_name: url-shortener-mongo
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis:7
        container_name: url-shortener-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data

volumes:
    mongo_data:
    redis_data:
